### ISSUE TITLE
swapping is broken

### ISSUE THREAD

**Issue by thinkier-tim** [autistic-ninja/Match3#2]
swapping without resulting in a viable match causes infinite swapping.

repro:
open game.
perform a swap that does not result in a match.
observe the resulting broken-ness.

**Comment by ColeRominger** [comment]
Are there errors in the log when this happens?

**Comment by thinkier-tim** [comment]
no, but that's because it's not an error. i forgot to make that happen only once per turn; will fix in a jiffy.
